include: package:very_good_analysis/analysis_options.7.0.0.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore
    lines_longer_than_80_chars: ignore

formatter:
  page_width: 100
