name: sentinel
description: Official Dart client for Sentinel authentication, providing seamless user authentication and session management integration for applications generated through Nexus.
version: 0.0.1
homepage: https://editorstack.com
repository: https://github.com/editorstack/sentinel-dart

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  drift: ^2.21.0
  drift_flutter: ^0.2.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  retrofit: ^4.4.1

dev_dependencies:
  build_runner: ^2.4.13
  drift_dev: ^2.21.2
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.5
  very_good_analysis: ^6.0.0
